// Generated by @lilium/compiler. Do not edit.
import { Template } from "@lilium/template";
import { CounterBehavior } from "../../support/counter.behavior.js";
import {
    Panel,
    PanelGap,
} from "../../support/layout.capabilities.js";
import {
    Button,
    ButtonLabel,
    Heading,
    HeadingText,
} from "../../support/content.capabilities.js";

/** @type {import("@lilium/template").TemplateDefinition<import("@lilium/template").ComponentTemplateStateFromDefinitionType<typeof CounterBehavior>>} */
const $template = Template.define({
    roots: [
        Template.node(Heading, {
            properties: [
                Template.value(HeadingText, "First"),
            ],
        }),
        Template.node(Panel, {
            properties: [
                Template.value(PanelGap, 12),
            ],
        }),
        Template.node(Button, {
            properties: [
                Template.value(ButtonLabel, "Last"),
            ],
        }),
    ],
});

export default Template.compose(CounterBehavior, $template);
