import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { Compiler } from "../../../src/index.js";

function decodeMappings(mappings: string) {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let source = 0;
    let sourceLine = 0;
    let sourceColumn = 0;
    const decoded: Array<{
        generatedLine: number;
        generatedColumn: number;
        sourceLine: number;
        sourceColumn: number;
    }> = [];

    for (const [generatedLine, line] of mappings.split(";").entries()) {
        let generatedColumn = 0;
        for (const segment of line.length === 0 ? [] : line.split(",")) {
            const values: number[] = [];
            let value = 0;
            let shift = 0;

            for (const character of segment) {
                const digit = alphabet.indexOf(character);
                value |= (digit & 31) << shift;
                if ((digit & 32) === 0) {
                    const negative = (value & 1) === 1;
                    values.push(negative ? -(value >> 1) : value >> 1);
                    value = 0;
                    shift = 0;
                } else {
                    shift += 5;
                }
            }

            generatedColumn += values[0] ?? 0;
            source += values[1] ?? 0;
            sourceLine += values[2] ?? 0;
            sourceColumn += values[3] ?? 0;
            assert.equal(source, 0);
            decoded.push({ generatedLine, generatedColumn, sourceLine, sourceColumn });
        }
    }

    return decoded;
}

describe("Compiler generation", () => {
    it("emits exact deterministic ESM with merged lexical imports", () => {
        const interpolation = "$" + "{controller.count.get()}";
        const generatedInterpolation = "$" + "{$state.controller.count.get()}";
        const source = [
            'behavior { CounterBehavior } from "./counter.js";',
            'primitives { Stack, Label } from "./ui.js";',
            'properties { Gap, Text } from "./ui.js";',
            "template {",
            "  node Stack {",
            "    value Gap = 8;",
            `    node Label { bind Text = \`Count: ${interpolation}\`; }`,
            "  }",
            "}",
        ].join("\n");

        const result = Compiler.compile(source, { filename: "src\\counter.lily" });
        const expected = [
            "// Generated by @lilium/compiler. Do not edit.",
            'import { Template } from "@lilium/template";',
            'import { CounterBehavior } from "./counter.js";',
            "import {",
            "    Gap,",
            "    Label,",
            "    Stack,",
            "    Text,",
            '} from "./ui.js";',
            "",
            "const $template = Template.define({",
            "    roots: [",
            "        Template.node(Stack, {",
            "            properties: [",
            "                Template.value(Gap, 8),",
            "            ],",
            "            children: [",
            "                Template.node(Label, {",
            "                    properties: [",
            `                        Template.binding(Text, ($state) => \`Count: ${generatedInterpolation}\`),`,
            "                    ],",
            "                }),",
            "            ],",
            "        }),",
            "    ],",
            "});",
            "",
            "export default Template.compose(CounterBehavior, $template);",
            "",
        ].join("\n");

        assert.deepEqual(result.diagnostics, []);
        assert.equal(result.output?.code, expected);
        assert.equal(result.output?.map.file, "src/counter.lily.js");
        assert.deepEqual(result.output?.map.sources, ["src/counter.lily"]);
        assert.deepEqual(result.output?.map.sourcesContent, [source]);
        assert.deepEqual(result.output?.map.names, []);
        assert.ok(result.output?.map.mappings);
        assert.equal(Object.isFrozen(result.output), true);
        assert.equal(Object.isFrozen(result.output?.map), true);
    });

    it("rewrites only executable binding roots and preserves exact source content", () => {
        const interpolation = "$" + "{inputs.label.get()}";
        const source = [
            'behavior { Behavior } from "./behavior.js";',
            'primitives { Root } from "./ui.js";',
            'properties { Data } from "./ui.js";',
            "template {",
            "  node Root {",
            `    bind Data = { controller: "controller", value: controller.value.get(), label: \`${interpolation} controller\` };`,
            "  }",
            "}",
        ].join("\r\n");

        const result = Compiler.compile(source, { filename: "binding.lily" });
        const code = result.output?.code ?? "";

        assert.match(
            code,
            /controller: "controller", value: \$state\.controller\.value\.get\(\), label: `\$\{\$state\.inputs\.label\.get\(\)\} controller`/,
        );
        assert.equal(code.includes("\r"), false);
        assert.equal(result.output?.map.sourcesContent[0], source);
    });

    it("maps imports, nodes, expressions, and composition to original positions", () => {
        const source = [
            'behavior { Behavior } from "./behavior.js";',
            'primitives { Root } from "./ui.js";',
            'properties { Value } from "./ui.js";',
            "template {",
            "  node Root {",
            "    bind Value = controller.value.get();",
            "  }",
            "}",
        ].join("\n");
        const result = Compiler.compile(source, { filename: "mapped.lily" });
        const decoded = decodeMappings(result.output?.map.mappings ?? "");
        const originalLocations = decoded.map(({ sourceLine, sourceColumn }) => [
            sourceLine,
            sourceColumn,
        ]);

        assert.ok(originalLocations.some(([line, column]) => line === 0 && column === 0));
        assert.ok(originalLocations.some(([line, column]) => line === 4 && column === 7));
        assert.ok(originalLocations.some(([line, column]) => line === 5 && column === 9));
        assert.ok(originalLocations.some(([line, column]) => line === 5 && column === 17));
    });

    it("produces byte-equivalent output and diagnostics for repeated compilation", () => {
        const source = [
            'behavior { Behavior } from "./behavior.js";',
            'primitives { Root } from "./ui.js";',
            'properties { Value } from "./ui.js";',
            "template { node Root { value Value = -1; } }",
        ].join("\n");

        const first = Compiler.compile(source, { filename: "stable.lily" });
        const second = Compiler.compile(source, { filename: "stable.lily" });

        assert.deepEqual(first, second);
        assert.equal(JSON.stringify(first), JSON.stringify(second));
    });

    it("returns diagnostics without partial output and rejects invalid API arguments", () => {
        const result = Compiler.compile("template {}", { filename: "invalid.lily" });

        assert.equal(result.output, undefined);
        assert.ok(result.diagnostics.length > 0);
        assert.throws(() => Compiler.compile(1 as never, { filename: "source.lily" }), TypeError);
        assert.throws(() => Compiler.compile("", {} as never), TypeError);
        assert.throws(() => Compiler.compile("", { filename: " " }), TypeError);
    });
});
