// Generated by @lilium/compiler. Do not edit.
import { Template } from "@lilium/template";
import { CounterBehavior } from "../../support/counter.behavior.js";
import {
    Label,
    LabelValue,
    Stack,
    StackGap,
} from "../../support/ui.capabilities.js";

/** @type {import("@lilium/template").TemplateDefinition<import("@lilium/template").ComponentTemplateStateFromDefinitionType<typeof CounterBehavior>>} */
const $template = Template.define({
    roots: [
        Template.node(Stack, {
            properties: [
                Template.value(StackGap, 4),
            ],
            children: [
                Template.node(Label, {
                    properties: [
                        Template.binding(LabelValue, ($state) => `Input: ${$state.inputs.initial.get()}`),
                    ],
                }),
            ],
        }),
    ],
});

export default Template.compose(CounterBehavior, $template);
