// Generated by @lilium/compiler. Do not edit.
import { Template } from "@lilium/template";
import { CounterBehavior } from "../../support/counter.behavior.js";
import {
    Action,
    ActionActivate,
    ActionLabel,
    Label,
    LabelValue,
    Stack,
    StackGap,
} from "../../support/ui.capabilities.js";

/** @type {import("@lilium/template").TemplateDefinition<import("@lilium/template").ComponentTemplateStateFromDefinitionType<typeof CounterBehavior>>} */
const $template = Template.define({
    roots: [
        Template.node(Stack, {
            properties: [
                Template.value(StackGap, +8),
            ],
            children: [
                Template.node(Label, {
                    properties: [
                        Template.binding(LabelValue, ($state) => $state.controller.count.get() > 0
                ? `Count: ${$state.controller.count.get()}`
                : "Empty"),
                    ],
                }),
                Template.node(Action, {
                    properties: [
                        Template.value(ActionLabel, `Increment`),
                        Template.binding(ActionActivate, ($state) => $state.controller.increment),
                    ],
                }),
            ],
        }),
    ],
});

export default Template.compose(CounterBehavior, $template);
