// Generated by @lilium/compiler. Do not edit.
import { Template } from "@lilium/template";
import { CounterBehavior } from "../../support/counter.behavior.js";
import {
    Stack,
    StackConfig,
} from "../../support/ui.capabilities.js";

/** @type {import("@lilium/template").TemplateDefinition<import("@lilium/template").ComponentTemplateStateFromDefinitionType<typeof CounterBehavior>>} */
const $template = Template.define({
    roots: [
        Template.node(Stack, {
            properties: [
                Template.value(StackConfig, { compact: false, values: [-8, +12, null, "wide", `fixed`] }),
            ],
        }),
    ],
});

export default Template.compose(CounterBehavior, $template);
