import type { CompilerOutput } from "../../compilation/contracts/compiler-output.contract.js";
import type { ICompilerImportIr } from "../../ir/contracts/internal/compiler-import-ir.contract.js";
import type { ICompilerModuleIr } from "../../ir/contracts/internal/compiler-module-ir.contract.js";
import type { ICompilerNodeIr } from "../../ir/contracts/internal/compiler-node-ir.contract.js";
import type { ICompilerPropertyIr } from "../../ir/contracts/internal/compiler-property-ir.contract.js";
import { CompilerSourceMapEncoder } from "../../source-map/runtime/compiler-source-map.encoder.js";
import type { TCompilerImportGroup } from "../types/internal/compiler-import-group.type.js";
import { GeneratedSourceWriter } from "./generated-source.writer.js";
import { LilyBindingEmitter } from "./lily-binding.emitter.js";

/** @description Generates deterministic readable ES2022 ESM and matching source maps from valid IR. */
export class LilyGenerator {
    /** @description Complete original Lily source retained by the generated source map. */
    readonly #source: string;

    /** @description Normalized caller-owned source identity. */
    readonly #filename: string;

    /** @description Forward-only generated code and mapping writer. */
    readonly #writer = new GeneratedSourceWriter();

    /**
     * @description Creates a generator for one validated source identity.
     * @param source - Complete original Lily source.
     * @param filename - Caller-owned source filename.
     */
    public constructor(source: string, filename: string) {
        this.#source = source;
        this.#filename = filename.replaceAll("\\", "/");
    }

    /**
     * @description Generates one immutable output pair from validated compiler IR.
     * @param ir - Error-free normalized compiler IR.
     * @returns Generated ES2022 ESM and matching source-map version 3 payload.
     */
    public generate(ir: ICompilerModuleIr): CompilerOutput {
        this.#writer.write("// Generated by @lilium/compiler. Do not edit.\n");
        this.#writer.write('import { Template } from "@lilium/template";\n');
        this.#writeImports(ir.imports);
        this.#writer.write("\n");
        this.#writer.write(
            `/** @type {import("@lilium/template").TemplateDefinition<import("@lilium/template").ComponentTemplateStateFromDefinitionType<typeof ${ir.behavior}>>} */\n`,
        );
        this.#writer.write("const $template = Template.define({\n");
        this.#writer.write("    roots: [\n");

        for (const root of ir.roots) {
            this.#writeNode(root, 2);
        }

        this.#writer.write("    ],\n");
        this.#writer.write("});\n\n");
        this.#writer.write("export default Template.compose(");
        const behaviorImport = ir.imports.find((declaration) => declaration.kind === "behavior");
        this.#writer.writeMapped(ir.behavior, behaviorImport?.span ?? ir.span);
        this.#writer.write(", $template);\n");

        const code = this.#writer.code();
        const mappings = new CompilerSourceMapEncoder().encode(
            this.#writer.mappings(),
            this.#writer.lineCount(),
        );

        return Object.freeze({
            code,
            map: Object.freeze({
                version: 3,
                file: `${this.#filename}.js`,
                sources: Object.freeze([this.#filename]),
                sourcesContent: Object.freeze([this.#source]),
                names: Object.freeze([]),
                mappings,
            }),
        });
    }

    /**
     * @description Merges imports by source appearance and emits lexical named specifiers.
     * @param imports - Ordered validated source imports.
     * @returns Nothing.
     */
    #writeImports(imports: readonly ICompilerImportIr[]): void {
        const groups = new Map<string, TCompilerImportGroup>();

        for (const declaration of imports) {
            const group = groups.get(declaration.source);
            if (group === undefined) {
                groups.set(declaration.source, {
                    source: declaration.source,
                    names: new Set(declaration.names),
                    span: declaration.span,
                });
            } else {
                for (const name of declaration.names) {
                    group.names.add(name);
                }
            }
        }

        for (const group of groups.values()) {
            const names = [...group.names].sort();
            this.#writer.writeMapped("import ", group.span);

            if (names.length === 1) {
                this.#writer.write(`{ ${names[0]} } from ${group.source};\n`);
                continue;
            }

            this.#writer.write("{\n");
            for (const name of names) {
                this.#writer.write(`    ${name},\n`);
            }
            this.#writer.write(`} from ${group.source};\n`);
        }
    }

    /**
     * @description Emits one normalized primitive node recursively.
     * @param node - Validated primitive node IR.
     * @param depth - Four-space indentation depth.
     * @returns Nothing.
     */
    #writeNode(node: ICompilerNodeIr, depth: number): void {
        const indentation = "    ".repeat(depth);
        this.#writer.write(`${indentation}Template.node(`);
        this.#writer.writeMapped(node.primitive, node.primitiveSpan);

        if (node.properties.length === 0 && node.children.length === 0) {
            this.#writer.write("),\n");
            return;
        }

        this.#writer.write(", {\n");

        if (node.properties.length > 0) {
            this.#writer.write(`${indentation}    properties: [\n`);
            for (const property of node.properties) {
                this.#writeProperty(property, depth + 2);
            }
            this.#writer.write(`${indentation}    ],\n`);
        }

        if (node.children.length > 0) {
            this.#writer.write(`${indentation}    children: [\n`);
            for (const child of node.children) {
                this.#writeNode(child, depth + 2);
            }
            this.#writer.write(`${indentation}    ],\n`);
        }

        this.#writer.write(`${indentation}}),\n`);
    }

    /**
     * @description Emits one static or binding Template property declaration.
     * @param property - Validated property IR.
     * @param depth - Four-space indentation depth.
     * @returns Nothing.
     */
    #writeProperty(property: ICompilerPropertyIr, depth: number): void {
        const indentation = "    ".repeat(depth);
        const operation = property.expression.kind === "value" ? "value" : "binding";
        this.#writer.write(`${indentation}Template.${operation}(`);
        this.#writer.writeMapped(property.property, property.propertySpan);
        this.#writer.write(", ");

        if (property.expression.kind === "bind") {
            this.#writer.write("($state) => ");
        }

        const expression =
            property.expression.kind === "bind"
                ? new LilyBindingEmitter(property.expression.source).emit()
                : property.expression.source.replace(/\r\n?|\n/g, "\n");
        this.#writer.writeMapped(expression, property.expression.span);
        this.#writer.write("),\n");
    }
}
